-- What is the total revenue generated by male & female customers

SELECT gender, SUM(purchase_amount) AS revenue
FROM user_behavior
GROUP BY gender; 

-- Which customers used a discount but still spent more than the average purchase amount 
select customer_id, purchase_amount
from user_behavior
where discount_applied = 'Yes' and purchase_amount >= (
	select avg(purchase_amount) from user_behavior
);

--  Which are the top 5 products with the hightest average review rating
select item_purchased, round(avg(review_rating), 2) as average_product_rating
from user_behavior
group by item_purchased
order by avg(review_rating) DESC
LIMIT 5;

--  Compare the average Purchase Amounts between Standard and Express Shipping
select shipping_type, round(avg(purchase_amount), 2)
from user_behavior
where shipping_type in ('Standard', 'Express')
group by shipping_type;

--  Do subscribed customers spend more? Compare average spend and total revenue between subcribers and non-subcribers
select subscription_status, 
round(avg(purchase_amount)) as average_purchase, 
SUM(purchase_amount) as total_revenue,
count(customer_id) as total_customer
from user_behavior
group by subscription_status
order by total_revenue, average_purchase;

-- Which 5 products have the highest percentage of purchases with discounts applied
select item_purchased,
	round(
    sum(
		case
			when discount_applied = 'Yes' then 1 else 0
        end
    ) / count(*) * 100, 2) as discount_rate
from user_behavior
group by item_purchased
order by discount_rate desc
limit 5;

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment
with customer_type as ( 
select customer_id, previous_purchases,
case when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
end as customer_segment
from user_behavior
)

select customer_segment, count(*) as 'Number of customers'
from customer_type
group by customer_segment;

-- What are the top 3 most purchased products within each category
with item_counts as (
select category, 
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from user_behavior
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Are customers who are repeat buyers (more than 5 previos purchase) also likely to subcribes
select subscription_status,
count(customer_id) as repeat_buyers
from user_behavior
where previous_purchases > 5
group by subscription_status;

-- What is the revenue contribution of each age group    
select age_group,
sum(purchase_amount) as total_revenue
from user_behavior
group by age_group
order by total_revenue DESC